CREATE TABLE `nwu_gradebook_data` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SITE_ID` varchar(255) NOT NULL DEFAULT '',
  `STUDENT_NUMBER` varchar(255) NOT NULL,
  `GRADE` double NOT NULL,
  `GRADABLE_OBJECT_ID` bigint(20) NOT NULL DEFAULT '0',
  `CREATED_DATE` datetime NOT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `STATUS` varchar(255) NOT NULL,
  `RETRY_COUNT` int(11) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
