CREATE TABLE NWU_GRADEBOOK_DATA (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    MODULE VARCHAR(255) NOT NULL,
    SITE_ID VARCHAR(255) NOT NULL,
    SITE_TITLE VARCHAR(255) NOT NULL,
    ASSESSMENT_NAME VARCHAR(255) NOT NULL,
    STUDENT_NUMBER VARCHAR(255) NOT NULL,
    GRADE DOUBLE NOT NULL,
    TOTAL_MARK DOUBLE NOT NULL,
    GRADABLE_OBJECT_ID BIGINT(20) NOT NULL,
    RECORDED_DATE DATETIME NOT NULL,
    DUE_DATE DATETIME NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    MODIFIED_DATE DATETIME,
    STATUS VARCHAR(255) NOT NULL,
    RETRY_COUNT INT(11),
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

   UNIQUE KEY `unique_popup_dismissed` (`user_eid`,`state`, `uuid`),
   FOREIGN KEY (uuid) REFERENCES pasystem_popup_screens(uuid),
   INDEX `user_eid` (`user_eid`),
   INDEX `state` (`state`)